/* HFO Explainer — English strings. window.STRINGS.en */
window.STRINGS = window.STRINGS || {};
window.STRINGS.en = {
  langName: "English",
  htmlLang: "en",
  locale: "en-GB",
  ui: {
    play: "▶ Play", pause: "⏸ Pause",
    realtimeAnim: "Real-time animation",
    readOn: "read on",
    forClinicians: "Working guide · for clinicians",
    langLabel: "Language",
  },
  nav: [
    { id: "sec-concept", label: "Concept" },
    { id: "sec-metaphor", label: "Metaphor" },
    { id: "sec-pistonjet", label: "Piston vs JET" },
    { id: "sec-indications", label: "Indications" },
    { id: "sec-simulator", label: "Simulator" },
    { id: "sec-convsim", label: "Mode trainer" },
    { id: "sec-flowsensor", label: "Flow sensor" },
    { id: "sec-protocol", label: "Protocol" },
    { id: "sec-hemo", label: "Hemodynamics" },
    { id: "sec-bloodgas", label: "Blood gas" },
    { id: "sec-start", label: "Start" },
    { id: "sec-adjust", label: "Correction" },
    { id: "sec-modes", label: "Modes" },
    { id: "sec-mistakes", label: "Mistakes" },
    { id: "sec-device", label: "Device" },
    { id: "sec-cheat", label: "Cheat sheet" },
  ],
  hero: {
    title: 'A hummingbird beats its wings<br><span class="hero-title-accent">80 times a second.</span><br>That\'s how <span class="hero-title-accent">HFO</span> breathes.',
    sub: "High-frequency oscillatory ventilation isn't \"normal ventilation, only faster.\" It's a completely different way to make the lungs work. Tiny, very rapid oscillations instead of big breaths. Here are the fundamentals in 15 minutes, plus a simulator where you can turn the dials and watch what changes.",
    meta: [
      { label: "Frequency", value: "5–15 ", unit: "Hz" },
      { label: "Stroke Volume", value: "0.2 ", unit: "mL step" },
      { label: "Piston", value: "13 ", unit: "µm precision" },
      { label: "DCO₂", value: "V", unit: "hfo", value2: "² × f" },
    ],
  },
  wave: {
    secLabel: "Concept · Conventional vs HFO",
    title: 'Conventional ventilation is <span class="muted">"breathe in, breathe out."</span><br>HFO is <span class="accent">"shimmering air."</span>',
    cmvTag: "Conventional · CMV", cmvRate: "25", cmvUnit: "breaths/min",
    cmvList: [
      "Big breaths, the usual way — in and back out",
      "Alveoli <b>stretch open and collapse</b> on every cycle",
      'Tidal volume <span class="num">6–8 mL/kg</span>',
      "Risk of baro/volutrauma in fragile lungs",
    ],
    hfoTag: "HFO · Humming Vue", hfoRate: "600+", hfoUnit: "per minute",
    hfoList: [
      "Lungs are <b>always open</b> on a constant MAP",
      "The piston pushes a tiny <b>Stroke Volume (SV)</b> that produces <b>V<sub>hfo</sub></b> — the volume actually delivered",
      'V<sub>hfo</sub> <span class="num">1.2–2 mL/kg</span> — smaller than dead space',
      "The lung doesn't \"move\" — it \"hums\"",
    ],
    mapCaption: "MAP — constant mean airway pressure",
  },
  metaphor: {
    secLabel: "Metaphor · Explain it like a child would get it",
    title: 'Picture a <span class="accent">hummingbird</span>.',
    lead: "When a hummingbird hovers, it beats its wings <b>50–80 times a second</b>. The wings barely move up and down — they just <b>shimmer</b>. But that's enough to stay airborne.",
    points: [
      { icon: "🪽", title: "Small movements, very frequent", body: 'That\'s HFO: instead of big breaths — tiny oscillations, up to <span class="num">15 times a second</span>.' },
      { icon: "🎈", title: "A balloon kept permanently inflated", body: "Alveoli are micro-balloons. On conventional ventilation we inflate and deflate them each time. On HFO we <b>keep them inflated</b> and gently shake them." },
      { icon: "🎵", title: "Sound inside an organ pipe", body: "Air in the tube vibrates like sound. Gases (O₂, CO₂) <b>mix through vibration</b>, not through \"arrive-and-leave.\"" },
      { icon: "👶", title: "Why it matters for the tiniest patients", body: "A newborn's lungs are like a thin film. Every big stretch is an injury. HFO <b>doesn't stretch</b> — it rocks." },
    ],
    quote: "A lung on HFO doesn't <b>breathe</b> — it <b>hums</b>. That's where the device gets its name — <b>Humming</b>.",
    quoteAttr: "— a simple rule to remember",
    hbLabel: "50–80 WINGBEATS PER SECOND", hbSub: "≈ the HFO oscillation rate",
  },
  indications: {
    secLabel: "Indications · When to use it",
    title: 'Six situations where HFO is the <span class="accent">right choice.</span>',
    sub: "HFO isn't \"the next step after conventional ventilation.\" It's a <b>different tool</b> for specific jobs. Learn these six — that covers 95% of real NICU cases.",
    items: [
      { code: "RDS", name: "Respiratory distress syndrome", desc: "Preterm. Immature lungs, little surfactant. HFO gives the alveoli a \"rest.\"", tag: "Preterm", color: "blue", icon: "👶" },
      { code: "MAS", name: "Meconium aspiration syndrome", desc: "Term infants. Meconium blocks small airways unevenly. HFO oscillations \"pump\" gas past the plugs.", tag: "Term", color: "amber", icon: "🫁" },
      { code: "PPHN", name: "Persistent pulmonary hypertension", desc: "Paired with iNO. HFO opens the capillary bed via a stable MAP.", tag: "+ iNO", color: "purple", icon: "💧" },
      { code: "Air leak", name: "Pneumothorax / interstitial emphysema", desc: "Air leak. Small oscillations don't \"inflate\" the hole — it gets a chance to close.", tag: "Leak", color: "red", icon: "💨" },
      { code: "CDH", name: "Congenital diaphragmatic hernia", desc: "Lung hypoplasia. The low volumes of HFO protect the little tissue there is.", tag: "Surgical", color: "cyan", icon: "⚕️" },
      { code: "Rescue", name: "After CMV fails", desc: "When conventional ventilation needs FiO₂ > 60% and MAP > 12 — switch to HFO before injury sets in.", tag: "Rescue", color: "teal", icon: "🆘" },
    ],
  },
  pistonJet: {
    secLabel: "Technology · Piston vs JET",
    title: 'There are two ways to do HFO. <span class="accent">They\'re not equal.</span>',
    sub: "Humming Vue is a <b>piston</b> device. The piston creates a real <b>portion of volume</b> that is delivered to the patient. The volume doesn't depend on pressure — so you control ventilation directly. JET ventilators work differently: they pump pressure, and the volume comes out \"however it comes out.\"",
    jetTag: "JET ventilation", jetTitle: "By pressure · turbulent flow",
    jetFlowLabel: "+ and − pressure · turbulence", jetFormula: "ΔP → Vt (depends on R and C)",
    jetBody: "The device creates <b>+ and − pressure</b> throughout the circuit → the flow becomes <b>turbulent</b> → power is lost and the airways are \"stretched.\" To deliver the same Vt, you need <b>more pressure = more amplitude</b>. But most of the pressure goes into holding the airways open — and there's <b>no certainty</b> the needed volume actually arrived. Risk of hypoventilation.",
    vueTag: "Humming Vue", vueTitle: "By volume · laminar flow",
    vueFlowLabel: "laminar flow · exact portion", vueFormula: "SV → V_hfo (exact, 13 µm)",
    vueBody: "The piston forms an <b>exact portion of volume (SV)</b> regardless of conditions → the flow is <b>laminar</b>, more efficient, with no excess pressure in the lungs. You don't set pressure. <b>ΔA is only an indicator of the energy</b> it took to overcome resistance (ETT, compliance). A may be higher or lower — but <b>the volume is delivered, guaranteed</b>.",
    rows: [
      { k: "Working principle", jet: "By pressure (ΔP)", vue: "By volume (Stroke Volume)" },
      { k: "Drive", jet: "A jet of gas under pressure", vue: "Precision piston · 13 µm" },
      { k: "Pressure in circuit", jet: "+ and − alternating throughout", vue: "Oscillation around a stable MAP" },
      { k: "Flow character", jet: "Turbulent → power loss", vue: "Laminar → efficient" },
      { k: "What you set", jet: "Pressure amplitude (ΔP)", vue: "A real portion of volume (SV)" },
      { k: "Cost of delivering Vt", jet: "Pressure in the airways rises", vue: "Only the ΔA indicator rises" },
      { k: "Volume guarantee", jet: "No — volume \"floats\"", vue: "Yes — delivered as a portion" },
      { k: "What you watch", jet: "The pressure trigger", vue: "Real V_hfo (flow sensor)" },
    ],
    thJet: "JET · by pressure", thVue: "Humming Vue · by volume",
    takeawayTitle: "Bottom line: assured volume vs a pressure you have to keep watching.",
    takeawayText: "Both technologies can ventilate well. But with <b>Humming Vue</b> you reach the goal with an <b>assured volume</b> — it's volume-controlled ventilation, and you don't overload the airways with pressure. With <b>JET</b> you constantly have to keep an eye on the pressure trigger: a swing in it → a swing in volume → ventilation that's now better, now worse.",
  },
  simulator: {
    secLabel: "Simulator · Humming Vue display",
    title: 'Turn the dials on the <span class="accent">right</span> — watch the waves<br>and the <span style="color:#F59E0B">auto-readings on the left</span>.',
    sub: "This is a simplified replica of the Humming Vue display. <b>SV</b> raises the amplitude of the pressure wave and the flow. <b>MAP</b> is the dashed horizontal line in the middle: it sets what the pressure oscillates around. <b>Hz</b> is the number of waves on screen. If the lungs stretch poorly or the ETT is pinched, <b>amplitude (ΔA)</b> rises on its own and <b>V<sub>hfo</sub></b> drops. The volume actually delivered is always smaller than SV — about 4–5× smaller in preterm infants, ~2.5× in adults.",
    catLabel: "Category", scenarioLabel: "Scenario",
    cats: { elbw: { label: "500–1000 g", sub: "ELBW · extremely preterm" }, infant: { label: "1–10 kg", sub: "Newborns · infants" }, pediatric: { label: "10 kg +", sub: "Children · adolescents" } },
    scenarios: { optimal: "Optimal", spontaneous: "Spont. breathing", lowCompliance: "Poor compliance", ettBlock: "ETT block" },
    tiles: {
      ampLabel: "Amplitude", ampSub: "ΔA · energy to overcome resistance",
      mapLabel: "MAP", mapSubHigh: "↑ climbing · overdistension", mapSubOk: "measured",
      vhfoLabel: "Vhfo", vhfoSub: (tgt, perkg) => `target ${tgt} · ${perkg} mL/kg`,
      dco2Label: "DCO₂", dco2Sub: (perkg) => `V_hfo² × f · ${perkg}/kg`,
    },
    vitals: { spo2: "SpO₂", pco2: "pCO₂", recruit: "Recruit", effic: "Effic.", efficUnit: "% SV→Vhfo" },
    knobs: {
      sv: "Stroke Vol", map: "MAP set", freq: "Frequency", fio2: "FiO₂",
      svHint: (tgt, perkg, svv) => `Target V_hfo ≈ ${tgt} mL (${perkg} mL/kg) → SV ≈ ${svv} mL`,
      mapHintOver: (d) => `MAP > optimum by ${d} cm → overdistension`,
      mapHintLow: "MAP below optimum → poor recruitment",
      mapHintOk: (opt) => `Optimum ≈ ${opt} cmH₂O`,
      hzHint: (h) => `Start ${h} Hz. Change rarely — it's the "coarse" dial.`,
      fio2HintHigh: "FiO₂ > 60% > 6 h — toxic", fio2HintOk: "Start 90–100%, drop by 5%",
    },
    modePill: "HFO",
    footer: ["Power", "Flush O₂", "HFO SI", "Panel Lock", "Alarm Suspend"],
    overlayBlock: "⚠  ETT BLOCK · LOW VOLUME ALERT",
    overlayCompl: "⚠  LOW COMPLIANCE · ΔA RISING",
    pvLoop: {
      label: "P–V loop · compliance",
      normal: "✓ Normal", caution: "⚠ Caution", alarm: "⚠ Alarm",
      goodTitle: "Ellipse · good compliance",
      goodDesc: "An open loop with good area: ΔA moderate, V_hfo on target. Gases mix efficiently. This is how it should look.",
      ettTitle: "Flat line · no volume",
      ettDesc: "ΔA is huge, V_hfo approaches zero. A big piston stroke — but no volume reaches the lungs. ETT block or disconnection. Suction immediately.",
      complTitle: "Narrow loop · poor compliance",
      complDesc: "ΔA rose, V_hfo dropped, DCO₂ crashed. The lungs stretch poorly. Recruitment maneuver: raise MAP to the opening point.",
      overTitle: "Overdistension · risk",
      overDesc: "MAP is high, measured MAP is climbing on its own. Alveoli are over-filled, capillary perfusion suffers. Lower MAP by 1 cm toward the optimum.",
      offTitle: "Off target",
      offDesc: (v, t) => `V_hfo = ${v} mL, target ≈ ${t} mL. Nudge SV in the right direction.`,
      ampCaption: (a) => `ΔA ≈ ${a} cmH₂O`, vhfoCaption: (v) => `V_hfo ≈ ${v} mL`,
    },
    noSensor: {
      eyebrow: "P–V loop unavailable", title: "No flow sensor > 10 kg",
      desc: "The adult circuit has no proximal flow sensor — the device doesn't measure <b>V<sub>hfo</sub></b> or <b>DCO₂</b> directly, and the pressure–volume loop can't be drawn. Without a sensor, rely on three things:",
      fallbacks: [
        "<b>Blood gas</b> — arterial sample, your main reference",
        "<b>Eye</b> — how far down the ribs the chest vibration is visible",
        "<b>ΔA</b> — a sharp amplitude rise = higher resistance",
      ],
    },
    diag: {
      secLabel: "Diagnostics by ΔA · what the amplitude tells you",
      title: 'ΔA is rising. <span class="accent">What happened?</span>',
      sub: "Amplitude is <b>the energy the device needs</b> to push SV through the ETT and open the lung. If it climbs on its own, there's an obstacle. Read <b>V<sub>hfo</sub></b> and <b>DCO₂</b> beside it — they tell you exactly where the problem is.",
      cardA: "A · ETT block",
      cardAAction: "A big piston stroke, no volume. The chest isn't vibrating.<br><b>→ SUCTION. Now.</b> Possible ETT obstruction.",
      cardB: "B · Poor compliance",
      cardBAction: "V<sub>hfo</sub> dipped slightly, but DCO₂ crashed (it's the square of V<sub>hfo</sub>).<br><b>→ Recruitment maneuver.</b> ↑ MAP to the opening point, then ↓ to optimum.",
    },
  },
  flowSensor: {
    secLabel: "Flow sensor · Certainty about volume",
    title: 'With a flow sensor you <span class="accent">see</span> the real volume.',
    sub: "The flow sensor (FS) is what turns \"I hope the volume got there\" into \"I know it did.\" It measures the real <b>V<sub>hfo</sub></b> and computes <b>DCO₂</b>. Many JET ventilators have no flow sensor — there you can't be sure the volume was actually delivered.",
    withTag: "With flow sensor · Humming Vue", withTitle: "You see the real V<sub>hfo</sub> and DCO₂",
    withList: [
      "The volume actually delivered, <b>V<sub>hfo</sub></b> — on screen, in real time",
      "<b>DCO₂ = V<sub>hfo</sub>² × f</b> — an exact ventilation index",
      "You see it instantly: volume fell → there's an obstacle, not your imagination",
      "You monitor the HFO process directly, not by proxy signs",
    ],
    withoutTag: "No sensor · many JET / circuit > 10 kg", withoutTitle: "Volume is invisible — assess it indirectly",
    withoutLead: "No V<sub>hfo</sub> or DCO₂ on screen. No certainty about real volume delivery — rely on three reference points:",
    fallbacks: [
      { icon: "🩸", title: "Blood gas — arterial sample", body: "Your main reference without a sensor. pH, pCO₂, pO₂, BE. Venous only for a trend in a pinch." },
      { icon: "👁", title: "Chest excursion — by eye", body: "Watch how far down the ribs the high-frequency vibration reaches. Normal: a fine \"humming\" wiggle down to the navel." },
      { icon: "📈", title: "Amplitude (ΔA)", body: "If ΔA rises sharply, that signals higher resistance (ETT, compliance). The volume may have dropped with it." },
    ],
  },
  protocol: {
    secLabel: "Protocol · Working stages with Humming Vue",
    title: 'Seven steps <span class="accent">from start to weaning</span>.',
    sub: "Pathology and blood gas first. Then MAP recruitment to the optimum. Then SV — confidently, by the gases. FiO₂ — only after you've found the MAP. Hz — barely touch it. Suction — only when you truly can't avoid it (and recruit again straight after). The move back to conventional ventilation — in stages, not a \"jump.\"",
    pitfallLabel: "⚠ Don't get caught:",
    steps: [
      { n: "01", title: "Start — assess the pathology", tone: "navy", icon: "🩺", summary: "Look at the patient first, then turn the dials.",
        points: [
          { k: "What the patient has", v: "RDS / MAS / PPHN / pulmonary hemorrhage / BPD — each pathology has its own starting MAP and Hz." },
          { k: "Weight", v: "Pick a category: 500–1000 g / 1–10 kg / >10 kg. Weight drives EVERYTHING — SV range, Hz, the V_hfo math, whether a flow sensor exists." },
          { k: "Blood gas", v: "Arterial sample is mandatory. Without it you're ventilating blind. pH, pCO₂, pO₂, BE." },
          { k: "Baseline", v: "Record before you start: SpO₂, HR, BP, urine output. Re-compare every 30–60 min in the first hours." },
        ],
        pitfall: "Don't start without an arterial line and stable hemodynamics. HFO is not a way to \"hide\" a patient." },
      { n: "02", title: "MAP recruitment — find the optimum", tone: "teal", icon: "⤴", summary: "MAP is the main oxygenation tool. Find the opening point → then the optimum point.",
        points: [
          { k: "Starting MAP", v: "2 cmH₂O above what it was on conventional ventilation (or 8–10 cm in a newborn with RDS). Keep FiO₂ at 90–100%." },
          { k: "Going up (recruit)", v: "↑ MAP by 1–2 cm every 2–3 minutes. Watch SpO₂: it SHOULD rise. As long as it rises — keep going." },
          { k: "Peak point", v: "You've reached maximum SpO₂ — that's the opening point. Note the MAP value." },
          { k: "Down to the optimum", v: "Drop MAP by 1 cm every 2–3 minutes. SpO₂ starts to fall — go back +1 cm. That's your optimum." },
          { k: "Sign of overdistension", v: "Measured MAP climbs on its own → alveoli are over-filled → perfusion suffers → SpO₂ falls, BP falls." },
        ],
        pitfall: "Don't rush the MAP wean. Better to sit at the optimum an extra 30 min and recheck blood gas than to re-open the lungs all over again." },
      { n: "03", title: "SV — turn it with confidence", tone: "amber", icon: "↔", summary: "Don't fear SV. It's the primary ventilation tool. Guides: V_hfo and blood gas.",
        points: [
          { k: "Starting SV", v: "So that V_hfo ≈ 1.7–2.0 mL/kg in severe disease. With spontaneous breathing or hypocapnia risk — 1.2–1.4 mL/kg." },
          { k: "Control — excursion", v: "The chest should clearly \"ring\" — a fine high-frequency vibration down to the navel." },
          { k: "Control — blood gas", v: "pCO₂ high → ↑ SV. pCO₂ low → ↓ SV. Change by 10–20%, recheck gas at 20–30 min." },
          { k: "DCO₂", v: "= V_hfo² × f. Quadratic dependence on volume! A small SV change has a big effect on CO₂." },
          { k: "Why with confidence", v: "The 13 µm piston gives an EXACT volume. You can't really get it wrong — you'll see it at once on V_hfo and blood gas. This isn't pressure that \"floats.\"" },
        ],
        pitfall: "If ΔA suddenly rises while V_hfo falls — don't turn SV higher. That's not a volume problem, it's mechanical. Go to step 06 (suction / compliance)." },
      { n: "04", title: "FiO₂ — drop it gradually", tone: "purple", icon: "O₂", summary: "Start 90–100%. Reduce by 5% once SpO₂ is stable.",
        points: [
          { k: "Starting FiO₂", v: "90–100% during recruitment, to take the oxygen variable out of the equation." },
          { k: "Weaning strategy", v: "Once you've found the optimal MAP and SpO₂ ≥ 92% steadily — drop FiO₂ by 5% every 30 min." },
          { k: "Toxicity threshold", v: "FiO₂ > 60% for more than 6 hours — oxygen toxicity to alveolar cells. Don't linger." },
          { k: "Main rule", v: "FiO₂ is not the main oxygenation tool. The main one is a properly chosen MAP. Good recruitment = less FiO₂." },
        ],
        pitfall: "Don't drop FiO₂ below 30% \"just in case\" — you need a reserve for suctioning and any maneuvers." },
      { n: "05", title: "Hz — barely touch it", tone: "blue", icon: "Hz", summary: "Hz is the \"coarse\" dial. Change it rarely. It keeps the system in tune.",
        points: [
          { k: "Starting Hz", v: "Preterm 15 Hz, term 10 Hz, children 7 Hz, adolescents 5 Hz. After that — barely touch it." },
          { k: "When to lower Hz", v: "Very severe hypercapnia, SV already maxed — lowering Hz increases tidal volume per cycle." },
          { k: "When to raise Hz", v: "Persistent hypocapnia, SV already at minimum — but this is a last resort." },
          { k: "Why \"coarse\"", v: "Hz changes EVERYTHING at once: DCO₂ (linearly), gas trapping (risk above 15), chest resonance." },
        ],
        pitfall: "Don't turn Hz \"to make SpO₂ look nice.\" Hz is the last dial you reach for. SV first, then MAP, then FiO₂." },
      { n: "06", title: "Suction — only when necessary", tone: "red", icon: "⚠", summary: "Every suction = loss of the optimal MAP. Do it only when you truly must.",
        points: [
          { k: "When mandatory", v: "ΔA rose, V_hfo and DCO₂ crashed → the ETT is plugged with secretions. The chest stopped vibrating." },
          { k: "What happens on suction", v: "Alveoli collapse → the PEEP effect is lost → the optimal MAP is lost. Afterward — recruit again." },
          { k: "Closed system", v: "Use a closed (in-line) suction catheter — the lungs don't lose pressure as dramatically as with open suction." },
          { k: "After suction", v: "Restore SpO₂ and MAP right away. 1–2 \"sustained inflations\" of 25–30 cmH₂O × 15 s, OR a slow MAP climb by 1 cm until SpO₂ returns to baseline." },
          { k: "Prevention", v: "Adequate humidification/warming of gas (37°C, 100% humidity), normovolemia. A dry circuit = thick secretions." },
        ],
        pitfall: "\"Prophylactic\" suction every 4 hours with no indication is HARMFUL. You open the system, lose MAP, recruit again. Only by indication." },
      { n: "07", title: "Coming off HFO — step by step", tone: "green", icon: "→", summary: "Don't rush to wean. Lungs must be stable, gases normal, hemodynamics off support.",
        points: [
          { k: "Readiness criteria", v: "FiO₂ ≤ 30–35%, MAP ≤ 8–10 cmH₂O, V_hfo stable > 6 hours, blood gas normal, hemodynamics off vasopressors." },
          { k: "Step 1 — lower MAP", v: "By 1 cm every 2–4 hours down to MAP ≈ 8 cm. Watch SpO₂. Don't fall below the recruitment point." },
          { k: "Step 2 — to conventional ventilation", v: "PEEP = the last MAP. PIP — by a tidal volume of 4–6 mL/kg. Rate 30–40/min (in a newborn)." },
          { k: "Step 3 — to non-invasive", v: "After a stable spell on conv. ventilation with PEEP 5–6 cm and FiO₂ ≤ 30% → nCPAP or nIPPV. Keep PEEP at the last level." },
          { k: "What NOT to do", v: "Jump straight from HFO to CPAP, skipping conventional ventilation — high risk of derecruitment and reintubation." },
        ],
        pitfall: "A step back is not a failure. If SpO₂ falls or ΔA rises after a MAP drop — go back to the previous level and wait 4–6 hours." },
    ],
  },
  hemo: {
    secLabel: "Hemodynamics · What you can't miss",
    title: 'Lungs and heart — <span class="accent">one system</span>.',
    sub: "HFO isn't only ventilation. Positive mean pressure in the chest presses on the heart and great vessels. If you're not watching hemodynamics, you're missing half the picture. These are general guides; specific decisions depend on the case and the patient.",
    signLabel: "Signs", recLabel: "Recommendation",
    items: [
      { head: "High MAP → venous return falls", body: "High intrathoracic pressure compresses the vena cava and right atrium. The heart gets less blood → cardiac output falls → BP falls → SpO₂ may \"drop\" not from the lungs but from perfusion.", sign: "BP ↓, HR ↑ compensatory, lactate ↑, urine output ↓", rec: "Before raising MAP, assess volume status. If there's reserve — a 10 mL/kg saline bolus. If not — be ready for a vasopressor.", tone: "amber" },
      { head: "The right ventricle suffers first", body: "High MAP compresses pulmonary capillaries → pulmonary vascular resistance rises → the right ventricle works against increased afterload. In newborns this is especially critical (PPHN).", sign: "Echo: RV dilation, tricuspid regurgitation, flattened interventricular septum", rec: "Echo monitoring when suspected. PPHN management: iNO 20 ppm, optimal oxygenation, avoid acidosis.", tone: "red" },
      { head: "Hypocapnia = cerebral vasoconstriction", body: "In preterm infants a low pCO₂ reduces cerebral blood flow → risk of PVL (periventricular leukomalacia). On HFO it's easy to \"over-blow\" because of the quadratic DCO₂ dependence.", sign: "pCO₂ < 35 mmHg — not normal, it's a danger", rec: "Lower SV right away. Target pCO₂ 45–55 (permissive hypercapnia). Check blood gas every 30–60 min in the first hours.", tone: "purple" },
      { head: "Preload and volume status", body: "HFO means constant positive pressure in the chest. A hypovolemic patient on HFO decompensates fast. Before starting — assess volume: capillary refill time, urine output, lactate.", sign: "CRT > 3 s, urine output < 1 mL/kg/h, lactate > 2 mmol/L", rec: "Top up before starting HFO or in parallel. Don't \"mask\" hypovolemia by raising MAP — it gets worse.", tone: "blue" },
      { head: "What to monitor continuously", body: "No less often than the device parameters. Hemodynamics and ventilation are one system.", sign: "Invasive BP · pre/post-ductal SpO₂ · HR · hourly urine · lactate every 4–6 h · echo on destabilization", rec: "Trends matter more than single readings. A 10% BP drop over an hour is a reason to look at what's changing in the lungs.", tone: "teal" },
    ],
  },
  bloodGas: {
    secLabel: "Blood gas · Arterial sample — mandatory",
    title: 'The cardinal rule of HFO —<br><span class="accent">timely blood-gas correction</span>.',
    sub: "On HFO you manage not what you hear through the stethoscope, but what the arterial blood shows. Without it — you ventilate blind. Venous blood is unreliable for oxygenation; take it only in extremis for a pCO₂ trend.",
    rules: [
      { when: "HFO start", what: "Arterial line — before switching to HFO. Blood gas before you start." },
      { when: "First 2 hours", what: "Blood gas every 30 min. Change SV and MAP by the gases, not \"by eye.\"" },
      { when: "Stabilization", what: "Blood gas every 4–6 hours. Plus — on any parameter change." },
      { when: "Targets", what: "pH 7.25–7.40 · pCO₂ 45–55 (permissive hypercapnia) · pO₂ 50–80 (newborns) · BE −4 to +4" },
    ],
  },
  howToStart: {
    secLabel: "Start · The first 30 minutes",
    title: 'How to <span class="accent">start</span> a patient on HFO.',
    sub: "Four steps, in order. Don't skip. Click a step to expand the detail.",
    pitfallLabel: "⚠ Catch",
    steps: [
      { title: "Optimize MAP", short: "Open the lungs", body: "Set MAP 1–2 cmH₂O above what it was on CMV. Raise it gradually by 1 cmH₂O every 2–3 minutes until SpO₂ improves. Then drop it by 1 cm at a time until SpO₂ starts to fall — that's the \"opening point.\" Set MAP 2 cm above it.", pitfall: "Too much MAP → overdistension → impaired perfusion → desaturation. Too little → atelectasis.", visual: "lungs-open", svgLabel: "OPEN" },
      { title: "Set frequency (f)", short: "By age", body: "Newborns: 10–15 Hz. Under 1 year: 8–10 Hz. Older: 6–8 Hz. Adults: 3–5 Hz. The smaller the patient, the higher the frequency.", pitfall: "Change frequency rarely. It's the \"coarse setting\" — it keeps the system in tune.", visual: "freq", svgLabel: "NEWBORN", svgUnit: "Hz" },
      { title: "Dial in Stroke Volume (SV)", short: "Main control", body: "On Humming Vue you turn SV (the piston's stroke volume), not amplitude. Start at 2 mL/kg (or 1.2–1.4 mL/kg with hypocapnia / spontaneous breathing). Step is 0.2 mL. Target: visible chest wiggle down to the navel. After 20–30 min — blood gas, adjust by 0.5–1 mL.", pitfall: "Amplitude (ΔP) is a consequence of SV, not the thing you turn.", visual: "shake", svgLabel: "TO THE NAVEL" },
      { title: "FiO₂ and verification", short: "Less is better", body: "Start FiO₂ at 90–100%, then drop by 5%. The main oxygenation tool is a properly chosen MAP combined with SV. Well-recruited lungs = less FiO₂. Target: SpO₂ 90–95% at FiO₂ < 60%. After 30 minutes — chest X-ray (8–9 ribs) and blood gas.", pitfall: "FiO₂ > 60% for more than 6 hours — toxic lung injury.", visual: "xray", svgLabel: "8–9 RIBS" },
    ],
  },
  adjust: {
    secLabel: "Correction · What to do if…",
    title: 'The blood gas spoke — <span class="accent">what do I turn?</span>',
    sub: "A simple cheat table. First decide the problem — is it oxygenation or ventilation? Then act.",
    cols: { problem: "Problem", cause: "Cause", fix: "What to do" },
    filters: { all: "All", oxy: "Oxygenation · SpO₂", vent: "Ventilation · CO₂", alarm: "Alarm" },
    tagLabels: { oxy: "oxygenation", vent: "ventilation", alarm: "alarm" },
    items: [
      { problem: "SpO₂ low", cause: "Lungs under-recruited or not enough O₂", fix: "↑ MAP by 1–2 cmH₂O · then ↑ FiO₂", which: "oxy" },
      { problem: "SpO₂ high, FiO₂ high", cause: "Ready to wean", fix: "↓ FiO₂ by 5% · then ↓ MAP by 1 cm", which: "oxy" },
      { problem: "pCO₂ high (hypercapnia)", cause: "Weak mixing — low V_hfo, low DCO₂", fix: "↑ SV by 0.5–1 mL · if maxed, ↓ f by 1 Hz", which: "vent" },
      { problem: "pCO₂ low (hypocapnia)", cause: "Over-ventilation · risk of alkalosis", fix: "↓ SV by 0.5–1 mL (aim for V_hfo 1.2–1.4 mL/kg)", which: "vent" },
      { problem: "No wiggle, chest not vibrating, DCO₂ → 0", cause: "Disconnection or blocked tube (ETT)", fix: "Suction · check ETT · watch ΔA and V_hfo on screen", which: "alarm" },
      { problem: "Sudden SpO₂ drop", cause: "Pneumothorax? Overdistension from high MAP?", fix: "Auscultate · urgent X-ray · check measured MAP", which: "alarm" },
      { problem: "ΔA rising, V_hfo and DCO₂ crashed", cause: "ETT blocked", fix: "Suction immediately", which: "alarm" },
      { problem: "ΔA rising, V_hfo dipped slightly, DCO₂ critically low", cause: "Poor airway compliance", fix: "Recruitment maneuver, ↑ MAP · optimize SV", which: "vent" },
    ],
  },
  mistakes: {
    secLabel: "Mistakes · DO & DON'T",
    title: 'Six things <span class="accent">everyone trips over.</span>',
    doLabel: "✓ Do", dontLabel: "✗ Don't", whyLabel: "Why",
    items: [
      { do: "Set MAP by the \"opening point\" — min to max, then back down", dont: "Copy the MAP from CMV — it'll be too low", why: "On HFO you must keep the lungs open continuously. Too low a MAP → poor compliance. Too high → overdistension → impaired perfusion → desaturation." },
      { do: "Change one thing at a time", dont: "Turn MAP, SV and f all at once", why: "You won't know which change helped and which one hurt." },
      { do: "Watch the chest and V_hfo / DCO₂", dont: "Go by numbers alone or by eye alone", why: "Visible wiggle down to the navel + rising DCO₂ are the best signs the device is working." },
      { do: "Blood gas at 20–30 minutes", dont: "At 5 minutes or after an hour", why: "Too early — it hasn't equilibrated. Too late — you'll miss decompensation." },
      { do: "Sedation, and sometimes paralysis", dont: "Fight the patient's active breathing", why: "Spontaneous breaths on HFO disrupt the whole physiology of the method." },
      { do: "Drop FiO₂ first when weaning", dont: "Slash MAP abruptly", why: "A sudden MAP drop → alveolar collapse → start all over again." },
    ],
  },
  device: {
    secLabel: "Device · Humming Vue",
    title: 'The <span class="accent">Humming Vue</span> itself.',
    sub: "Hover over the numbers to learn what's what.",
    specTitle: "Technical spec",
    spec: [
      { k: "Drive type", v: "Piston, 13 µm" }, { k: "Origin", v: "90% Japan" },
      { k: "Flow", v: "Laminar (volume-based)" }, { k: "Stroke Volume", v: "0–160 mL · 0.2 mL step" },
      { k: "MAP", v: "3–40 cm H₂O" }, { k: "Frequency", v: "5–17 Hz" },
      { k: "Patients", v: "500 g → children" }, { k: "Auto-readings", v: "ΔA · MAP · V_hfo · DCO₂" },
    ],
    parts: [
      { id: "screen", label: "Screen · 4 settings + 4 automatic readings", desc: "Large touchscreen. On the right — 4 adjustable parameters (SV, MAP, f, FiO₂). On the left — 4 auto-readings: ΔA (amplitude), measured MAP, V_hfo, DCO₂. ΔP is not set — it's a consequence of SV." },
      { id: "piston", label: "13 µm piston · the heart of the device", desc: "A precision piston accurate to 13 micrometers. 90% of components — Japan. It produces an exact Stroke Volume (SV) — the stroke that forms V_hfo. Volume-based principle → laminar flow → precise delivery regardless of compliance." },
      { id: "circuit", label: "Breathing circuit", desc: "Heated humidifier + a dedicated HFO circuit. Not to be confused with a conventional ventilator tube." },
      { id: "controls", label: "Controls for the 4 parameters", desc: "MAP · SV · f · FiO₂ — the four main dials. SV (Stroke Volume) is the primary ventilation control, resolution 0.2 mL. Amplitude ΔA is displayed as a consequence — it isn't set directly." },
      { id: "alarm", label: "Audible and visual alarm", desc: "Distinguishes critical (red) from informational (amber) alarms. DCO₂ → 0 plus a sharp ΔA rise — critical alarm: possible ETT obstruction." },
    ],
  },
  cheat: {
    secLabel: "Cheat sheet · Keep it next to the device",
    title: 'HFO in <span class="accent">12 lines.</span>',
    cards: [
      { icon: "🪽", text: "<b>HFO = hummingbird.</b> Small fast oscillations instead of big breaths." },
      { icon: "⚖️", text: "<b>Piston vs JET.</b> Humming Vue is volume-based (assured). JET is pressure-based (volume \"floats,\" watch the trigger)." },
      { icon: "🎈", text: "<b>Lungs stay open all the time.</b> No inflate-deflate. Held on MAP." },
      { icon: "🎯", text: "<b>4 settings on the right:</b> SV · MAP · f · FiO₂." },
      { icon: "📊", text: "<b>4 auto-readings on the left:</b> ΔA · measured MAP · V<sub>hfo</sub> · DCO₂. Judge the work by these." },
      { icon: "🧮", text: "<b>DCO₂ = V<sub>hfo</sub>² × f.</b> The exact number you assess the process by." },
      { icon: "🫁", text: "<b>SpO₂ → MAP and FiO₂.</b> MAP matters more: find the \"opening point.\"" },
      { icon: "💨", text: "<b>CO₂ → SV (main) and f.</b> SV forms V<sub>hfo</sub>. Step 0.2 mL." },
      { icon: "⚠️", text: "<b>ΔA ↑ + V<sub>hfo</sub>/DCO₂ → 0</b> = ETT blocked → suction immediately." },
      { icon: "⏱", text: "<b>Blood gas at 20–30 min.</b> Not sooner, not later." },
      { icon: "📉", text: "<b>Weaning:</b> FiO₂ first by 5%, then MAP by 1 cm. Never the other way." },
      { icon: "📡", text: "<b>Flow sensor = certainty.</b> With it you see real V<sub>hfo</sub> and DCO₂. Without it — blood gas + eye + ΔA." },
    ],
    footerMeta: ["Humming Vue · HFO · Bundle C — Neonatal", "Tashkent · 2026", "swanston.uz"],
  },
  ventModes: {
    secLabel: "Other modes · Patient management",
    title: 'HFO isn\'t the only mode.<br><span class="accent">A/C · VG · SIMV · CPAP · NIV.</span>',
    sub: "Humming Vue and most ICU ventilators also run conventional modes. The principles are shared: <b>oxygenation = PEEP/MAP + FiO₂</b>, <b>ventilation (CO₂) = volume × rate</b>. Below — starting settings, blood-gas correction and weaning for each mode. Specifics depend on the patient and unit protocol.",
    pitfallLabel: "⚠ Pitfall:",
    cols: { when: "When", params: "Starting settings", vent: "CO₂ · ventilation", oxy: "O₂ · oxygenation", wean: "Weaning / escalation" },
    modes: [
      {
        key: "ac", abbr: "A/C", name: "Assist Control", type: "Every breath supported", tone: "navy",
        tagline: "Every patient breath (above trigger) is taken to the target PIP or Vt. A backup rate covers apnea.",
        when: "Acute respiratory failure, full support, sedated or unstable patient, early phase of ventilation.",
        params: [
          { k: "Rate (backup)", v: "By age: neonate 40–60, child 20–30, adolescent 12–18/min." },
          { k: "PIP / Vt", v: "PIP to a tidal volume of <b>4–6 mL/kg</b>. On volume A/C you set Vt directly." },
          { k: "PEEP", v: "5–6 cmH₂O (by oxygenation)." },
          { k: "Ti", v: "Neonate 0.30–0.35 s, child 0.6–0.8 s." },
          { k: "Trigger · FiO₂", v: "Sensitive flow trigger. FiO₂ by SpO₂." },
        ],
        vent: "Minute ventilation = <b>Vt × rate</b>. ↑pCO₂ → ↑PIP (or Vt) and/or ↑rate. ↓pCO₂ → the reverse. Change one thing, recheck gas at 20–30 min.",
        oxy: "↓SpO₂ / pO₂ → ↑PEEP by 1–2 cm and/or ↑FiO₂. PEEP is the main recruiter, FiO₂ the top-up.",
        wean: "Lower PIP/rate by gas → move to SIMV, or straight to NIV/CPAP once stable.",
        pitfall: "With a high <b>spontaneous</b> rate — hyperventilation and alkalosis; watch for auto-PEEP (shorten Ti or drop rate).",
      },
      {
        key: "vg", abbr: "VG", name: "Volume Assured / Volume Guarantee", type: "Pressure-limited, volume-targeted", tone: "teal",
        tagline: "Pressure-limited, volume-targeted ventilation. The ventilator auto-adjusts PIP breath to breath to deliver the set Vt. Protects against volutrauma.",
        when: "Unstable compliance (surfactant dosing), preterm RDS, BPD prevention — anywhere volume stability matters.",
        params: [
          { k: "Target Vt", v: "<b>4–6 mL/kg</b> (start ~4.5–5 mL/kg)." },
          { k: "Pmax (limit)", v: "5 cm above working PIP — the safety ceiling." },
          { k: "PEEP", v: "5–6 cmH₂O." },
          { k: "Rate · Ti", v: "As in A/C, by age." },
          { k: "FiO₂", v: "By SpO₂, start by severity." },
        ],
        vent: "High pCO₂ → ↑ target Vt by 0.5 mL/kg and/or ↑ rate. Low → ↓ Vt. <b>The ventilator moves PIP itself</b> — your job is to hold the target volume.",
        oxy: "PEEP and FiO₂ as in A/C. Volume has little effect on oxygenation.",
        wean: "As compliance improves, PIP <b>falls automatically</b> → lower rate → extubate to NIV/CPAP.",
        pitfall: "PIP pinned at Pmax with Vt not reached → ETT leak, obstruction or poor compliance. Find the cause, <b>don't raise Pmax blindly</b>.",
      },
      {
        key: "simv", abbr: "SIMV", name: "Synchronized IMV", type: "Mandatory + spontaneous", tone: "purple",
        tagline: "A set number of synchronized mandatory breaths; between them the patient breathes spontaneously — usually with pressure support (PS).",
        when: "Weaning from ventilation, partial support, a patient with steady spontaneous drive.",
        params: [
          { k: "Mandatory rate", v: "Lower than A/C (≈60% of it)." },
          { k: "PIP / Vt", v: "On the mandatory breaths — 4–6 mL/kg." },
          { k: "Pressure Support", v: "<b>8–10 cmH₂O</b> over PEEP on spontaneous breaths." },
          { k: "PEEP", v: "5 cmH₂O." },
          { k: "Ti · FiO₂", v: "By age; FiO₂ by SpO₂." },
        ],
        vent: "High pCO₂ → ↑ mandatory rate or PIP/PS. Low → ↓ mandatory rate — the main weaning route.",
        oxy: "PEEP and FiO₂ as usual.",
        wean: "Gradually ↓ mandatory rate to 10–15/min → move to CPAP+PS → extubate.",
        pitfall: "Too little support for a weak patient → work of breathing rises, fatigue. Watch tachypnea, retractions, rising pCO₂.",
      },
      {
        key: "cpap", abbr: "CPAP", name: "Continuous PAP", type: "Constant pressure, spontaneous breathing", tone: "blue",
        tagline: "A single constant positive pressure; the patient breathes entirely on their own. No mandatory breaths — it's FRC support, not ventilation.",
        when: "Mild/moderate RDS (early use), post-extubation, apnea of prematurity (+ caffeine).",
        params: [
          { k: "CPAP pressure", v: "<b>5–7 cmH₂O</b> (start 6)." },
          { k: "FiO₂", v: "By SpO₂." },
          { k: "Interface", v: "Nasal prongs / mask. A good seal is critical." },
          { k: "Rate / PIP", v: "None — the patient breathes alone." },
        ],
        vent: "CPAP barely clears CO₂ — it depends on the patient's own effort. If pCO₂ rises and pH drops, that's a <b>signal to escalate</b> (NIV/NIPPV or intubate), not \"raise the CPAP.\"",
        oxy: "↓pO₂ → ↑CPAP to 7–8 cm and/or ↑FiO₂.",
        wean: "↓FiO₂ below 30% → ↓ pressure to 5 cm → remove once stable.",
        pitfall: "CPAP > 8 cm → over-distension, air leak, gastric distension. Don't \"hide\" worsening failure under CPAP.",
      },
      {
        key: "niv", abbr: "NIV", name: "NIPPV / Non-invasive ventilation", type: "Two pressure levels, no intubation", tone: "amber",
        tagline: "Non-invasive support with two pressure levels (IPAP/EPAP), or PEEP with intermittent peaks — via prongs or mask.",
        when: "Respiratory failure without an immediate intubation indication, post-extubation (reintubation prevention), rising work of breathing on CPAP.",
        params: [
          { k: "IPAP / PIP", v: "14–20 cmH₂O (by severity)." },
          { k: "EPAP / PEEP", v: "5–6 cmH₂O." },
          { k: "Rate (backup)", v: "20–40/min by age." },
          { k: "Ti · FiO₂", v: "By age; FiO₂ by SpO₂." },
        ],
        vent: "High pCO₂ → ↑ IPAP (ΔP = IPAP − EPAP) by 2 cm and/or ↑ rate. Low → ↓ IPAP.",
        oxy: "↓pO₂ → ↑EPAP by 1–2 cm and/or ↑FiO₂.",
        wean: "↓ IPAP and rate → move to CPAP → prongs.",
        pitfall: "Mask leak = ineffective support and false alarms; gastric distension (place a tube). No improvement in 1–2 h → <b>intubate, don't wait</b>.",
      },
    ],
  },
  advisor: {
    secLabel: "ABG advisor · Starting-settings calculator",
    title: 'Enter <span style="color:#A8F03C">weight</span> and <span style="color:#F59E0B">blood gas</span> —<br>get the start, an ABG read and corrections.',
    sub: "An advanced model: pick the patient profile, weight and FiO₂, enter the blood gas — and the advisor returns <b>starting settings</b> for the chosen mode, an <b>acid-base interpretation</b> and <b>concrete corrective actions</b>. Decision support, not a substitute for clinical judgement.",
    patientTitle: "Patient and mode",
    profileLabel: "Profile",
    profiles: {
      preterm: { label: "Preterm", sub: "Extremely/very preterm · permissive hypercapnia, lower SpO₂ targets" },
      term: { label: "Term", sub: "Term newborn · standard targets" },
      infant: { label: "Infant", sub: "Infant / young child" },
      ped: { label: "Child", sub: "Child / adolescent · near-adult targets" },
    },
    weightLabel: "Weight",
    fio2Label: "FiO₂",
    modeLabel: "Ventilation mode",
    modeOpts: { hfo: "HFO", ac: "A/C", vg: "VG", simv: "SIMV", cpap: "CPAP", niv: "NIV" },
    abgTitle: "Blood gas (ABG) · arterial",
    abgFields: { ph: "pH", pco2: "pCO₂", po2: "pO₂", hco3: "HCO₃⁻" },
    hco3Note: (h, b) => `HCO₃⁻ ${h === "—" ? "—" : h} mmol/L · BE ${b === "—" ? "—" : (b >= 0 ? "+" + b : b)} (derived from pH/pCO₂ if left blank)`,
    presetLabel: "Quick scenarios",
    presets: [
      { label: "Normal", values: { ph: 7.36, pco2: 45, po2: 70, hco3: "" } },
      { label: "Resp. acidosis", values: { ph: 7.22, pco2: 62, po2: 55, hco3: "" } },
      { label: "Hypoxemia", values: { ph: 7.33, pco2: 44, po2: 38, hco3: "" } },
      { label: "Hypocapnia", values: { ph: 7.50, pco2: 26, po2: 95, hco3: "" } },
      { label: "Metab. acidosis", values: { ph: 7.20, pco2: 30, po2: 75, hco3: 12 } },
      { label: "Mixed", values: { ph: 7.10, pco2: 60, po2: 48, hco3: 16 } },
    ],
    interpTitle: "ABG interpretation",
    invalid: "Fill in pH, pCO₂ and pO₂ to interpret.",
    recTitle: "What to do — recommendations",
    recTags: { vent: "CO₂ / ventilation", oxy: "O₂ / oxygenation", met: "metabolic", crit: "critical", ok: "on target" },
    startTitle: (mode) => `Starting settings · ${mode}`,
    targetsTitle: "Target values",
    tl: { ph: "pH", pco2: "pCO₂ mmHg", po2: "pO₂ mmHg", spo2: "SpO₂" },
    disclaimer: "⚠ Educational decision-support model. Starting values are general-rule guidance; always cross-check the clinical picture, X-ray, unit protocol and trends. Not a substitute for a clinician's orders.",
    units: { pct: "%", cmh2o: "cmH₂O", hz: "Hz", bpm: "/min", s: "s", ml: "mL", mlkg: "mL/kg", kg: "kg", mmhg: "mmHg", mmol: "mmol/L" },
    startRows: { map: "MAP", hz: "Frequency (Hz)", sv: "SV · Vhfo target", fio2: "FiO₂", rate: "Rate", pip: "PIP", peep: "PEEP", ti: "Ti", vt: "Target Vt", pmax: "Pmax (limit)", ps: "Pressure Support", cpap: "CPAP pressure", iface: "Interface", ipap: "IPAP", epap: "EPAP" },
    svNote: (vhfo) => `turn to chest wiggle · Vhfo target ≈ ${vhfo} mL (1.7 mL/kg)`,
    toVt: (vt) => `to Vt ${vt} mL`,
    ifaceVal: "prongs / mask",
    ax: {
      normalAB: "Acid-base status normal",
      respAcidosis: "Respiratory acidosis", respAlkalosis: "Respiratory alkalosis",
      metAcidosis: "Metabolic acidosis", metAlkalosis: "Metabolic alkalosis",
      mixedAcidosis: "Mixed acidosis (resp. + metab.)", mixedAlkalosis: "Mixed alkalosis (resp. + metab.)",
      compRespAcidosis: "Compensated respiratory acidosis", compRespAlkalosis: "Compensated respiratory alkalosis",
      acidemiaOther: "Acidemia", alkalemiaOther: "Alkalemia",
      partial: "partially compensated", uncompensated: "uncompensated", compensated: "fully compensated",
      phLabel: "pH", co2Label: "pCO₂", o2Label: "pO₂",
      co2High: "hypercapnia", co2Low: "hypocapnia", co2Ok: "on target",
      o2Low: "hypoxemia", o2High: "above target", o2Ok: "on target",
    },
    actions: {
      hfo: {
        co2Up: "<b>↑ SV</b> by 10–20% (forms Vhfo; DCO₂ = Vhfo²×f). If SV is maxed — <b>↓ Hz by 1 Hz</b>. Recheck ABG at 20–30 min.",
        co2Down: "<b>↓ SV</b> by 10–20% — aim for Vhfo 1.2–1.4 mL/kg. Hypocapnia is dangerous (cerebral vasoconstriction).",
        o2Up: "<b>↑ MAP</b> by 1–2 cmH₂O (recruit) and/or <b>↑ FiO₂</b>. MAP is the main oxygenation tool.",
        o2Down: "Good recruitment — <b>↓ MAP</b> by 1 cm toward optimum.",
        o2DownF: "<b>↓ FiO₂</b> by 5% (above 30% there's room to drop), then ↓ MAP.",
      },
      ac: {
        co2Up: "<b>↑ PIP</b> by 2–3 cm (or ↑ Vt) and/or <b>↑ rate</b>. Minute ventilation = Vt × f.",
        co2Down: "<b>↓ rate</b> or ↓ PIP. Watch auto-PEEP and the patient's own rate.",
        o2Up: "<b>↑ PEEP</b> by 1–2 cm and/or <b>↑ FiO₂</b>.",
        o2Down: "<b>↓ PEEP</b> toward 5 cm with stable SpO₂.",
        o2DownF: "<b>↓ FiO₂</b> by 5% first, then ↓ PEEP.",
      },
      vg: {
        co2Up: "<b>↑ target Vt</b> by 0.5 mL/kg and/or <b>↑ rate</b>. The vent raises PIP itself — check it isn't pinned at Pmax.",
        co2Down: "<b>↓ target Vt</b> by 0.5 mL/kg or ↓ rate.",
        o2Up: "<b>↑ PEEP</b> by 1–2 cm and/or <b>↑ FiO₂</b>.",
        o2Down: "<b>↓ PEEP</b> toward 5 cm with stable SpO₂.",
        o2DownF: "<b>↓ FiO₂</b> by 5% first, then ↓ PEEP.",
      },
      simv: {
        co2Up: "<b>↑ mandatory rate</b> or ↑ PIP/PS. Don't move to weaning while hypercapnic.",
        co2Down: "<b>↓ mandatory rate</b> — the main SIMV weaning route.",
        o2Up: "<b>↑ PEEP</b> by 1–2 cm and/or <b>↑ FiO₂</b>.",
        o2Down: "<b>↓ PEEP</b> toward 5 cm with stable SpO₂.",
        o2DownF: "<b>↓ FiO₂</b> by 5% first, then ↓ PEEP.",
      },
      cpap: {
        co2Up: "CPAP doesn't clear CO₂. Boost the patient's own drive (caffeine) — but if acidosis builds, <b>escalate to NIV/NIPPV or intubate</b>.",
        co2Down: "Hypocapnia on CPAP — assess tachypnea/pain/agitation; usually no setting change needed.",
        o2Up: "<b>↑ CPAP</b> to 7–8 cm and/or <b>↑ FiO₂</b>.",
        o2Down: "<b>↓ FiO₂</b>, then ↓ CPAP toward 5 cm.",
        o2DownF: "<b>↓ FiO₂</b> by 5% first, then ↓ CPAP.",
      },
      niv: {
        co2Up: "<b>↑ IPAP</b> by 2 cm (raises ΔP = IPAP − EPAP) and/or <b>↑ rate</b>. Check the mask seal.",
        co2Down: "<b>↓ IPAP</b> by 2 cm.",
        o2Up: "<b>↑ EPAP</b> by 1–2 cm and/or <b>↑ FiO₂</b>.",
        o2Down: "<b>↓ EPAP</b> toward 5 cm with stable SpO₂.",
        o2DownF: "<b>↓ FiO₂</b> by 5% first, then ↓ EPAP.",
      },
    },
    notes: {
      metAcid: "Metabolic component: <b>the ventilator won't fix it</b>. Find the cause — perfusion, lactate, sepsis, HCO₃ loss. Cautious compensatory ventilation is acceptable, but don't over-blow.",
      metAlk: "Metabolic alkalosis: assess diuretics, Cl⁻/K⁺ loss, alkali excess. Correction is causal, not ventilatory.",
      cpapFail: "<b>CPAP isn't clearing</b> CO₂ with acidemia → escalate: NIV/NIPPV or intubate. Don't lose time.",
      severeAcid: "<b>Severe acidemia (pH < 7.20).</b> Act fast, assess hemodynamics and cause; consider escalating the mode.",
      severeAlk: "<b>Severe alkalemia (pH > 7.55).</b> Reduce ventilation, look for a metabolic cause.",
      hypocapnia: "In a preterm, <b>hypocapnia is especially dangerous</b> (PVL risk). Reduce minute ventilation without delay.",
      onTarget: "✓ ABG within target for the profile. Hold settings, recheck gas on schedule. Consider weaning once stable.",
    },
  },
  convSim: {
    secLabel: "Mode trainer · Humming Vue screen",
    title: 'Practise the other modes —<br><span class="accent">A/C · VG · SIMV · CPAP · NIV.</span>',
    sub: "The same screen as HFO, but for conventional modes. Pick a mode, weight and lung scenario, turn the knobs on the <b>right</b> — and watch the three traces (pressure · flow · volume) and the readings on the left respond. <b>SpO₂</b> follows MAP and FiO₂, <b>pCO₂</b> follows minute ventilation (Vt × rate).",
    modeLabel: "Mode", catLabel: "Weight", scenarioLabel: "Lung scenario",
    modes: { ac: "A/C", vg: "VG", simv: "SIMV", cpap: "CPAP", niv: "NIV" },
    scenarios: { optimal: "Normal", lowCompliance: "Low compliance", highResistance: "High resistance", leak: "Leak" },
    lanes: { paw: "Paw · Pressure", pawUnit: "cmH₂O", flow: "Flow", flowUnit: "L/min", vol: "Volume", volUnit: "mL" },
    overlayLeak: "⚠  CIRCUIT LEAK · VOLUME LOST",
    overlayVtHigh: "⚠  Vt HIGH · VOLUTRAUMA RISK",
    overlayVtLow: "⚠  Vt LOW · HYPOVENTILATION",
    overlayLimit: "⚠  PIP AT Pmax · Vt NOT REACHED",
    units: { bpm: "/min", cmh2o: "cmH₂O", s: "s", ml: "mL", mlkg: "mL/kg" },
    tiles: {
      pip: "PIP", pipSub: "peak pressure", pipAuto: "PIP (auto)", pipAutoSub: "vent holds Vt", pipAutoLimit: "↑ pinned at Pmax!",
      ipap: "IPAP", cpap: "CPAP",
      pmean: "MAP", pmeanSub: "mean airway pressure · oxygenation",
      vt: "Vt expired", vtSub: (vtkg) => `delivered · ${vtkg} mL/kg`,
      mve: "MVe", mveSub: (rr) => `minute volume · RR ${rr}`,
    },
    vitals: { spo2: "SpO₂", pco2: "pCO₂", vtkg: "Vt/kg", cdyn: "Cdyn", cdynUnit: "mL/cmH₂O" },
    knobs: {
      rate: "Rate", rateHint: (mve) => `Minute volume ≈ ${mve} L/min`,
      pip: "PIP", pipHint: (vtkg) => `Driving → Vt ${vtkg} mL/kg (target 4–6)`,
      peep: "PEEP", peepHint: (pm) => `MAP ≈ ${pm} cmH₂O · oxygenation`,
      ti: "Ti", tiHint: "Inspiratory time. Shorter Ti → less Vt and MAP.",
      fio2: "FiO₂", fio2HintHigh: "FiO₂ > 60% > 6 h — toxic", fio2HintOk: "Start by severity, wean by 5%",
      vt: "Target Vt", vtHint: (vtkg, pip) => `Delivered ${vtkg} mL/kg · PIP auto ${pip}`,
      ps: "Pressure Support", psHint: "Supports spontaneous breaths above PEEP",
      cpap: "CPAP", cpapHint: (spo2) => `Lung recruitment · SpO₂ ${spo2}%`,
      ipap: "IPAP", ipapHint: (vtkg) => `ΔP=IPAP−EPAP → Vt ${vtkg} mL/kg`,
      epap: "EPAP", epapHint: "= PEEP · oxygenation",
      pipAutoLimit: "Vt not met — find the cause", pipAutoOk: "Within Pmax",
    },
    footer: ["Power", "Insp. Hold", "Exp. Hold", "Panel Lock", "Alarm Suspend"],
    coach: {
      ac: { title: "A/C — Assist Control", body: "Turn <b>PIP</b> and <b>rate</b> by CO₂ (minute volume = Vt × f). Hold <b>Vt 4–6 mL/kg</b>. Oxygenate via <b>PEEP</b> and FiO₂. Switch on \"low compliance\" — watch Vt drop at the same PIP." },
      vg: { title: "VG — volume guarantee", body: "You set the <b>target Vt</b>; the vent auto-adjusts <b>PIP</b> (see the auto tile). Switch on \"low compliance\" — PIP rises to hold the volume. If it pins at Pmax, Vt won't be reached and an alarm shows." },
      simv: { title: "SIMV — mandatory + spontaneous", body: "The trace shows large <b>mandatory breaths</b> and small <b>spontaneous PS breaths</b> between them. Lower the <b>mandatory rate</b> to wean; <b>PS</b> supports the patient's own breaths." },
      cpap: { title: "CPAP — constant pressure", body: "No mandatory breaths — only small <b>spontaneous</b> swings around CPAP. Affect oxygenation via <b>CPAP</b> and FiO₂. CO₂ is barely controllable — hypercapnia means escalate to NIV." },
      niv: { title: "NIV — non-invasive, 2 levels", body: "Two levels: <b>IPAP</b> (peak) and <b>EPAP</b> (baseline). CO₂ → ΔP = IPAP − EPAP and rate; oxygenation → EPAP and FiO₂. Switch on \"leak\" — part of the volume is lost and an alarm shows." },
    },
  },
};
